project_id = "wrdeomgtkbehvbfhiprm"

[functions.mqtt-webhook]
verify_jwt = false

[functions.master-login]
verify_jwt = false

[functions.master-login-secure]
verify_jwt = false

[functions.verify-master-session]
verify_jwt = false

[functions.verify-master-session-secure]
verify_jwt = false

[functions.master-logout]
verify_jwt = false

[functions.master-kpis]
verify_jwt = false

[functions.device-command]
verify_jwt = true

[functions.mqtt-credentials]
verify_jwt = true
